### ISSUE TITLE
'conda' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by becky11380** [CWTSLeiden/CSSS#2]
After I installed and launched Aconda Prompt successfully, I navigated to the directory to which I unzipped the repository using cd Documents\CWTS. However, after I typed "conda env create -f local/environment.yml" to set up new environment CSSS, I got the error, 'conda' is not recognized as an internal or external command, operable program or batch file.

Does anybody have idea what the problem is? Thanks!

**Comment by vtraag** [comment]
Perhaps you accidentally opened the "Command Prompt" instead of the "Anaconda Prompt"?

**Comment by becky11380** [comment]
> Perhaps you accidentally opened the "Command Prompt" instead of the "Anaconda Prompt"?

Thanks for your reply. It is in the Anaconda Prompt. 
![error](https://user-images.githubusercontent.com/8577679/55458525-c9230080-561f-11e9-85ab-3a89b1918a26.png)

**Comment by vtraag** [comment]
Hmm, that is unfortunate, it seems that something has gone wrong with the installation. Could you try to remove Anaconda Python and reinstall it? There are further troubleshooting tips at http://docs.anaconda.com/anaconda/user-guide/troubleshooting/.

**Comment by becky11380** [comment]
> Hmm, that is unfortunate, it seems that something has gone wrong with the installation. Could you try to remove Anaconda Python and reinstall it? There are further troubleshooting tips at http://docs.anaconda.com/anaconda/user-guide/troubleshooting/.

Thank you and I will reinstall.

**Comment by becky11380** [comment]
> Hmm, that is unfortunate, it seems that something has gone wrong with the installation. Could you try to remove Anaconda Python and reinstall it? There are further troubleshooting tips at http://docs.anaconda.com/anaconda/user-guide/troubleshooting/.

It works successfully after I reinstall anaconda! Thanks a lot!

**Comment by vtraag** [comment]
Great!
